apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: application
  project: default
  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 16.4.14
