apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: crds.enabled
          value: 'true'
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
