apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  source:
    chart: ingress-nginx
    helm:
      parameters:
        - name: controller.replicaCount
          value: '2'
      values: |-
        controller:
          extraArgs:
            enable-ssl-passthrough: ""
          config:
            # Enables Modsecurity
            enable-modsecurity: "true"

            # Update ModSecurity config and rules
            modsecurity-snippet: |
              # this enables the default OWASP Core Rule Set
              Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf

              # Enable prevention mode. Options: DetectionOnly,On,Off (default is DetectionOnly)
              SecRuleEngine On

              # Enable scanning of the request body
              SecRequestBodyAccess On
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
