apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: longhorn-system
  project: default
  source:
    chart: longhorn
    helm:
      parameters:
        - name: csi.attacherReplicaCount
          value: '2'
        - name: csi.provisionerReplicaCount
          value: '2'
        - name: csi.resizerReplicaCount
          value: '2'
        - name: csi.snapshotterReplicaCount
          value: '2'
      values: |
        global:
          nodeSelector:
            kubernetes.io/arch: arm64
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          storageMinimalAvailablePercentage: 10
          systemManagedComponentsNodeSelector:
            kubernetes.io/arch: arm64
        persistence:
          defaultClassReplicaCount: 2
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.0
