apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-root
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: application
    repoURL: https://github.com/bzKKday/oce-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
