apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: infra
    repoURL: https://github.com/bzKKday/oce-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
